# Generated by Django 4.2.6 on 2023-10-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0001_initial'),
    ]

    operations = [
    ]
