# Generated by Django 4.2.6 on 2023-10-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("publishedDate", models.DateField(auto_now_add=True)),
                ("price", models.FloatField()),
                ("imgUrl", models.CharField(max_length=255)),
                ("category_name", models.CharField(max_length=255)),
                ("stars", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
