# Generated by Django 4.2.6 on 2023-10-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_auto_20231025_0739"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="buys",
            field=models.IntegerField(default=0),
        ),
    ]
